# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  templateapi:
    image: templateapi
    build:
      context: .
      dockerfile: Customers/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5054:5054
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=TrinitySecured
      - POSTGRES_USER=Trinity
      - POSTGRES_DB=CustomersDB
